### ISSUE TITLE
Access out of project directory

### ISSUE THREAD

**Issue by synalysis** [dillonkearns/elm-pages-3-alpha-starter#10]
When I download this repo and uncompress it in the Downloads folder (macOS), then run `npm install` and `./node_modules/.bin/elm-pages build`, the build stops with the following error message:
```
(node:20117) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
vite v4.0.4 building for production...
<script src="/elm.js"> in "/elm-stuff/elm-pages/index.html" can't be bundled without type="module" attribute
✓ 5 modules transformed.
dist/manifest.json                   0.33 kB
dist/elm-stuff/elm-pages/index.html  0.60 kB
dist/assets/index-21fb42a2.css       0.12 kB │ gzip: 0.13 kB
dist/assets/index-83013fcf.js        2.18 kB │ gzip: 1.14 kB
Trace: glob error [Error: EPERM: operation not permitted, scandir '/Users/<user>/Downloads'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/<user>/Downloads'
}
{"type":"error","title":"UNEXPECTED ERROR","path":"/Users/<user>/Downloads/elm-pages-3-alpha-starter-main/node_modules/elm-pages/generator/dead-code-review/elm.json","message":["I ran into an unexpected error. Please open an issue at the following link:\n  https://github.com/jfmengels/node-elm-review/issues/new\n\nPlease include this error message and as much detail as you can provide. If you\ncan, please provide a setup that makes it easy to reproduce the error. That will\nmake it much easier to fix the issue.\n\nBelow is the error that was encountered.\n--------------------------------------------------------------------------------\nError: EPERM: operation not permitted, scandir '/Users/<user>/Downloads'"]}

    at Module.run (file:///Users/<user>/Downloads/elm-pages-3-alpha-starter-main/node_modules/elm-pages/generator/src/build.js:215:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (file:///Users/<user>/Downloads/elm-pages-3-alpha-starter-main/node_modules/elm-pages/generator/src/cli.js:49:7)
glob error [Error: EPERM: operation not permitted, scandir '/Users/<user>/Downloads'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/<user>/Downloads'
}
{"type":"error","title":"UNEXPECTED ERROR","path":"/Users/<user>/Downloads/elm-pages-3-alpha-starter-main/node_modules/elm-pages/generator/dead-code-review/elm.json","message":["I ran into an unexpected error. Please open an issue at the following link:\n  https://github.com/jfmengels/node-elm-review/issues/new\n\nPlease include this error message and as much detail as you can provide. If you\ncan, please provide a setup that makes it easy to reproduce the error. That will\nmake it much easier to fix the issue.\n\nBelow is the error that was encountered.\n--------------------------------------------------------------------------------\nError: EPERM: operation not permitted, scandir '/Users/<user>/Downloads'"]}

```

Copying the folder first to `/tmp` avoids the error but I assume the access outside the project folder still happens, is just not prevented by the OS.

Maybe this message could be avoided somehow?
`<script src="/elm.js"> in "/elm-stuff/elm-pages/index.html" can't be bundled without type="module" attribute
`

**Comment by dillonkearns** [comment]
Hey @synalysis, thanks for reporting the issue, I pushed a fix that locks the version of the elm-review NPM package to fix this. Should be good now 👍 

I'm not sure how to remove that warning message from Vite about elm.js, but I think that would be better in a separate issue in the elm-pages repo (not the starter repo). I'd welcome a pull request on that one if anybody wants to try removing it.
