### ISSUE TITLE
Page displayed but functionality stopped

### ISSUE THREAD

**Issue by rolojf** [dillonkearns/elm-pages-3-alpha-starter#4]
Updated to the latest changes and something is wrong.
The simple mobile menu open and close  functionality stopped working.
But no error is shown and the page is indeed displayed. 

On the console of the browser (firefox) I get a couple things to look at:
1. The following error at elm-pages.js:13:15 where the following code is `const app = Elm.Main.init({...` :
```
Uncaught ReferenceError: Elm is not defined
    loadContentAndInitializeApp http://localhost:1234/elm-pages.js:13
    appPromise http://localhost:1234/elm-pages.js:60
    appPromise http://localhost:1234/elm-pages.js:59
    setup http://localhost:1234/elm-pages.js:58
    <anonymous> http://localhost:1234/elm-pages.js:106

```
and the warning: `Loading failed for the <script> with source “http://localhost:1234/elm.js”. localhost:1234:7:1`.

2. Also an error in hmr.js:
```
Firefox can’t establish a connection to the server at http://localhost:1234/stream. hmr.js:9:16
```
3,  Some other error  at the console:
```
GET http://localhost:1234/elm.js
[HTTP/1.1 500 Internal Server Error 5ms]

GET
	http://localhost:1234/elm.js
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred1.63 KB (1.45 KB size)
Referrer Policystrict-origin-when-cross-origin
```

4. Another one:
`Firefox can’t establish a connection to the server at http://localhost:1234/stream. hmr.js:9:16`

In elm-pages submodule I am at:
```
commit 2d9695f55122ccae1031f74df7bce1401f85ac4a (HEAD)
Author: Dillon Kearns <dillon@incrementalelm.com>
Date:   Sat Apr 9 08:11:45 2022 -0700

    Use logout effect from greet page.
```

**Comment by rolojf** [comment]
I also tried `npx elm-pages dev --debug` and no elm debug enabled on the page.

**Comment by rolojf** [comment]
Wait, something is off.  I reverted my to the bare repository and the error does`t appear any more..
I`ll do more tests.

**Comment by rolojf** [comment]
After erasing `./.elm-pages`, `elm-stuff` and `node-modules` and reinstalling all again. The errors went away.
